IEEE_BCN_SB_WS/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from IEEE_BCN_SB_WS import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^web/', include('web.urls', namespace="web")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url

from . import views

app_name = 'web'

urlpatterns = [
    # ex: ~/
    url(r'^$', views.index, name='index'),
    # ex: ~/contact
    url(r'^contact$', views.contact, name='contact'),
    # ex: ~/contact/send
    url(r'^contact/send$', views.contactSend, name='contactSend'),
    # ex: ~/buran
    url(r'^buran$', views.buran, name='buran'),
    # ex: ~/buran
    url(r'^ieee$', views.ieee, name='ieee'),
    # ex: ~/visitas
    url(r'^visitas$', views.visitas, name='visitas'),
    # ex: ~/visitas/5/
    url(r'^visitas/(?P<visita_id>[0-9]+)/$', views.visita, name='visita'),
    # ex: ~/cursos
    url(r'^cursos$', views.cursos, name='cursos'),
    # ex: ~/cursos/5/
    url(r'^cursos/(?P<curso_id>[0-9]+)/$', views.curso, name='curso'),
    # ex: ~/proyectos
    url(r'^proyectos$', views.proyectos, name='proyectos'),
    # ex: ~/proyecto/5/
    url(r'^proyectos/(?P<proyecto_id>[0-9]+)/$', views.proyecto, name='proyecto'),
    # ex: ~/conferencias
    url(r'^conferencias$', views.conferencias, name='conferencias'),
    # ex: ~/conferencia/5/
    url(r'^conferencias/(?P<conferencia_id>[0-9]+)/$', views.conferencia, name='conferencia'),

]

web/templates/web/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Developed By M Abdur Rokib Promy">
    <meta name="author" content="cosmic">
    <meta name="keywords" content="Bootstrap 3, Template, Theme, Responsive, Corporate, Business">
    <link rel="shortcut icon" href="{% static "web/img/favicon.jpg" %}">

    <title>
      {% block title %}IEEE BCN SB{% endblock title %}
    </title>


    {% block preScripts %}
    <!-- Bootstrap core CSS -->
    <link href="{% static "web/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "web/css/theme.css" %}" rel="stylesheet">
    <link href="{% static "web/css/bootstrap-reset.css" %}" rel="stylesheet">
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet">-->

    <!--external css-->
    <link href="{% static "web/css/font-awesome.css" %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static "web/css/flexslider.css" %}"/>
    <link href="{% static "web/css/jquery.bxslider.css" %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static "web/css/animate.css" %}">
    <link rel="stylesheet" href="{% static "web/css/owl.carousel.css" %}">
    <link rel="stylesheet" href="{% static "web/css/owl.theme.css" %}">

    <link href="{% static "web/css/superfish.css" %}" rel="stylesheet" media="screen">
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->


    <!-- Custom styles for this template -->
    <link href="{% static "web/css/component.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "web/css/style.css" %}" rel="stylesheet">
    <link href="{% static "web/css/style-responsive.css" %}" rel="stylesheet" />

    <link type="text/css" href="{% static "web/css/parallax-slider.css" %}"  rel="stylesheet" />
    <script type="text/javascript" src="{% static "web/js/modernizr.custom.28468.js" %}">
    </script>

    {% endblock preScripts %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js">
    </script>
    <script src="js/respond.min.js">
    </script>
    <![endif]-->
  </head>

  <body>
    <!--header start-->
    <header class="head-section">
      <div class="navbar navbar-default navbar-static-top container">
          <div class="navbar-header">
              <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'web:index' %}">
                <img src="{% static "web/img/IEEE_logo.png" %}" alt="Logo IEEE" height="75" width="230"/>
              </a>
          </div>
          <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li>
                      <a href="{% url 'web:ieee' %}">IEEE</a>
                  </li>
                  <li class="dropdown">
                      <a class="dropdown-toggle" data-close-others="false" data-delay="0" data-hover=
                      "dropdown" data-toggle="dropdown" >Actividades <i class="fa fa-angle-down"></i>
                      </a>
                      <ul class="dropdown-menu">
                          <li>
                              <a href="{% url 'web:proyectos' %}">Proyectos</a>
                          </li>
                          <li>
                              <a href="{% url 'web:cursos' %}">Cursos</a>
                          </li>
                          <li>
                              <a href="{% url 'web:visitas' %}">Visitas</a>
                          </li>
                          <li>
                              <a href="{% url 'web:conferencias' %}">Conferencias</a>
                          </li>
                          <li>
                              <a href="{% url 'web:buran' %}">Buran</a>
                          </li>
                      </ul>
                  </li>
                  <!--
                  <li>
                      <a href="ieee.html">Agenda</a>
                  </li>
                  -->
                  <li>
                      <a href="{% url 'web:contact' %}">Contacto</a>
                  </li>

                  <!-- <li><input class="form-control search" placeholder=" Search" type="text"></li> -->
              </ul>
          </div>
      </div>
    </header>
    <!--header end-->

 	{% block content %}Empty base {% endblock content %}

    <!--footer start-->
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-sm-3 address wow fadeInUp" data-wow-duration="2s" data-wow-delay=".1s">
            <h1>
              Información de contacto
            </h1>
            <address>
              <p><i class="fa fa-home pr-10"></i>Edificio Omega, S-105</br>  Campus Nord UPC</p>
              <p><i class="fa fa-globe pr-10"></i>08034 - Barcelona </p>
              <p><i class="fa fa-phone pr-10"></i>Phone : 93 413 76 56 </p>
              <p><i class="fa fa-envelope pr-10"></i>Email :   <a href="javascript:;"> ieee@ieee.upc.edu</a></p>
            </address>
          </div>
          <div class="col-lg-3 col-sm-3">
            <div class="page-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".5s">
              <h1>
                Our Company
              </h1>
              <ul class="page-footer-list">
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="about.html">About Us</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="faq.html">Support</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="service.html">Service</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="privacy-policy.html">Privacy Policy</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="career.html">We are Hiring</a>
                </li>
                <li>
                  <i class="fa fa-angle-right"></i>
                  <a href="terms.html">Term & condition</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-sm-3">
            <div class="text-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".7s">
              <h1>
                Text Widget
              </h1>
              <p>
                This is a text widget.Lorem ipsum dolor sit amet.
                This is a text widget.Lorem ipsum dolor sit amet.
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- footer end -->
    <!--small footer start -->
    <footer class="footer-small">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-6 pull-right">
                    <ul class="social-link-footer list-unstyled">
                        <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".1s"><a target="_blank" href="http://www.facebook.com/IEEEBcnStudentBranch"><i class="fa fa-facebook"></i></a></li>
                        <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".2s"><a target="_blank" href="http://www.twitter.com/IEEE_SB_BCN"><i class="fa fa-twitter"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                  <div class="copyright">
                    <p>&copy; Copyright - Acme Theme by cosmic.</p>
                  </div>
                </div>
            </div>
        </div>
    </footer>
    <!--small footer end-->

    <!-- js placed at the end of the document so the pages load faster
<script src="js/jquery.js">
</script>
-->
    <script src="{% static "web/js/jquery-1.8.3.min.js" %}">
    </script>
    <script src="{% static "web/js/bootstrap.min.js" %}">
    </script>
    <script type="text/javascript" src="{% static "web/js/hover-dropdown.js" %}">
    </script>
    <script defer src="{% static "web/js/jquery.flexslider.js" %}">
    </script>
    <script type="text/javascript" src="{% static "web/js/jquery.bxslider.js" %}">
    </script>

    <script type="text/javascript" src="{% static "web/js/jquery.parallax-1.1.3.js" %}">
    </script>
    <script src="{% static "web/js/wow.min.js" %}">
    </script>
    <script src="{% static "web/js/owl.carousel.js" %}">
    </script>

    <script src="{% static "web/js/jquery.easing.min.js" %}">
    </script>
    <script src="{% static "web/js/link-hover.js" %}">
    </script>
    <script src="{% static "web/js/superfish.js" %}">
    </script>
    <script type="text/javascript" src="{% static "web/js/jquery.cslider.js" %}">
    </script>
    <script type="text/javascript">
      $(function() {

        $('#da-slider').cslider({
          autoplay    : true,
          bgincrement : 100
        });

      });
    </script>



    <!--common script for all pages-->
    <script src="{% static "web/js/common-scripts.js" %}">
    </script>

    {% block postScripts %}

    <script type="text/javascript">
      jQuery(document).ready(function() {


        $('.bxslider1').bxSlider({
          minSlides: 5,
          maxSlides: 6,
          slideWidth: 360,
          slideMargin: 2,
          moveSlides: 1,
          responsive: true,
          nextSelector: '#slider-next',
          prevSelector: '#slider-prev',
          nextText: 'Onward →',
          prevText: '← Go back'
        });

      });


    </script>


    <script>
      $('a.info').tooltip();

      $(window).load(function() {
        $('.flexslider').flexslider({
          animation: "slide",
          start: function(slider) {
            $('body').removeClass('loading');
          }
        });
      });

      $(document).ready(function() {

        $("#owl-demo").owlCarousel({

          items : 4

        });

      });

      jQuery(document).ready(function(){
        jQuery('ul.superfish').superfish();
      });

      new WOW().init();


    </script>
    {% endblock postScripts %}
  </body>
</html>

web/templates/web/conferencia.html
{% extends 'web/base.html' %}

{% block title %}Conferencia | IEEE BCN SB{% endblock title %}


  {% block content %}

    <!--breadcrumbs start-->
    <div class="breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-sm-4">
            <h1>
                {{ conferencia.title }}
            </h1>
          </div>
          <div class="col-lg-8 col-sm-8">
            <ol class="breadcrumb pull-right">
              <li>
                <a href="{% url 'web:index' %}">
                  Inicio
                </a>
              </li>
              <li>
                <a href="{% url 'web:conferencias' %}">
                  Conferencias
                </a>
              </li>
              <li class="active">
                 Conferencia
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->


    <!--container start-->
    <div class="container">
      <div class="row">
        <!--blog start-->
        <div class="col-lg-9 ">

        <div class="blog-item">
            <div class="row">
              <div class="col-lg-2 col-sm-2">
                <div class="date-wrap">
                  <span class="date">
                    {{ conferencia.date_start.day }}
                  </span>
                  <span class="month">
                    {{ conferencia.month }} {{ conferencia.date_start.year }}
                  </span>
                </div>

              </div>
              <div class="col-lg-10 col-sm-10">
                  {% if conferencia.img %}
                  <div class="blog-img">
                    <img src="{{ conferencia.img.url }}" alt="Imagen de la conferencia"/>
                  </div>
                  {% endif %}

              </div>
            </div>
            <div class="row">
              <div class="col-lg-2 col-sm-2 text-right">
                <div class="author">
                  Por
                  <a href="#">
                    {{ username }}
                  </a>
                </div>
              </div>
              <div class="col-lg-10 col-sm-10">
                <h1>
                    {{ conferencia.title }}
                </h1>
                <p>
                    {% autoescape off %}
                      {{ conferencia.description }}
                    {% endautoescape %}
                </p>
              </div>
            </div>
          </div>

        </div>

        <div class="col-lg-3">
          <div class="blog-side-item">
           <!-- Side content -->

          </div>
        </div>

        <!--blog end-->
      </div>

    </div>
    <!--container end-->

{% endblock content %}

{% block postScripts %}
  {{ block.super }}
      <script>
      wow = new WOW(
        {
          boxClass:     'wow',      // default
          animateClass: 'animated', // default
          offset:       0          // default
        }
      )
        wow.init();
    </script>
{% endblock postScripts %}

web/templates/web/conferencias.html
{% extends 'web/base.html' %}

{% block title %}Conferencias | IEEE BCN SB{% endblock title %}


  {% block content %}



<!--breadcrumbs start-->
    <div class="breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-sm-4">
            <h1>
              Conferencias
            </h1>
          </div>
          <div class="col-lg-8 col-sm-8">
            <ol class="breadcrumb pull-right">
              <li>
                <a href="{% url 'web:index' %}">
                  Inicio
                </a>
              </li>
              <li class="active">
                Conferencias
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->


    <!--container start-->
    <div class="container">
      <div class="row">
        <!--blog start-->
        <div class="col-lg-9 ">

      {% if conferencias_list %}
    <ul>
    {% for conferencia in conferencias_list %}
        <div class="blog-item">
            <div class="row">
              <div class="col-lg-2 col-sm-2">
                <div class="date-wrap">
                  <span class="date">
                    {{ conferencia.date_start.day }}
                  </span>
                  <span class="month">
                    {{ conferencia.month }} {{ conferencia.date_start.year }}
                  </span>
                </div>

              </div>
              <div class="col-lg-10 col-sm-10">
                  {% if conferencia.img %}
                  <div class="blog-img">
                    <img src="{{ conferencia.img.url }}" alt="Imagen de la conferencia"/>
                  </div>
                  {% endif %}

              </div>
            </div>
            <div class="row">
              <div class="col-lg-2 col-sm-2 text-right">
                <div class="author">
                  Por
                  <a href="#">
                    {{ username }}
                  </a>
                </div>
              </div>
              <div class="col-lg-10 col-sm-10">
                <h1>
                  <a href="{% url 'web:conferencia' conferencia.id %}">
                    {{ conferencia.title }}
                  </a>
                </h1>
                <p>
                    {% autoescape off %}
                      {{ conferencia.summary }}
                    {% endautoescape %}
                </p>
                <a href="{% url 'web:conferencia' conferencia.id %}" class="btn btn-primary">
                  Mas información
                </a>
              </div>
            </div>
          </div>
    {% endfor %}
    </ul>
    {% else %}
        <h2>No hay conferencias que mostrar... por ahora.</h2>
    {% endif %}

        </div>

        <div class="col-lg-3">
          <div class="blog-side-item">
           <!-- Side content -->

          </div>
        </div>

        <!--blog end-->
      </div>

    </div>
    <!--container end-->

{% endblock content %}

{% block postScripts %}
  {{ block.super }}
      <script>
      wow = new WOW(
        {
          boxClass:     'wow',      // default
          animateClass: 'animated', // default
          offset:       0          // default
        }
      )
        wow.init();
    </script>
{% endblock postScripts %}

web/templates/web/contact.html
{% extends 'web/base.html' %}

{% block title %}Contacto | IEEE BCN SB{% endblock title %}

{% block preScripts %}
  {{ block.super }}
{% endblock preScripts %}

  {% block content %}


    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&AMP;sensor=false">
    </script>
    <!--breadcrumbs start-->
    <div class="breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-sm-4">
            <h1>
              Contacto
            </h1>
          </div>
          <div class="col-lg-8 col-sm-8">
            <ol class="breadcrumb pull-right">
              <li>
                <a href="{% url 'web:index' %}">
                  Inicio
                </a>
              </li>
              <li class="active">
                Contacts
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->



    <!--container start-->
    <div class="container">

      <div class="row">
        <div class="col-lg-5 col-sm-5 address">
          <section class="contact-infos">
            <h4 class="title custom-font text-black">
              DIRECCIÓN
            </h4>
            <address>
              Edificio Omega, S-105
              <br>
              Barcelona (08034), Spain
            </address>
          </section>
          <section class="contact-infos">
            <h4>
              CONTACTO
            </h4>
            <p>
              <i class="fa fa-phone pr-10">
              </i>
              +034-934137656
            </p>

            <p>
              <i class="fa fa-envelope pr-10">
              </i>
              ieee@ieee.upc.edu
            </p>

          </section>
        </div>
        <div class="col-lg-7 col-sm-7 address">
          <h4>
            Envíenos una línea para que podamos saber de usted
          </h4>
          <div class="contact-form">
            <form role="form"action="{% url 'web:contactSend' %}" method="post">
            {% csrf_token %}
              <div class="form-group">
                <label for="name">
                  Nombre
                </label>
                <input type="text" placeholder="" name="name" id="name" class="form-control">
              </div>
              <div class="form-group">
                <label for="email">
                  Email
                </label>
                <input type="text" placeholder="" name="email" id="email" class="form-control">
              </div>
              <div class="form-group">
                <label for="phone">
                  Mensaje
                </label>
                <textarea placeholder="" name="msg" rows="5" class="form-control">
                </textarea>
              </div>
              <button class="btn btn-info" type="submit">
                Enviar
              </button>
            </form>

          </div>
        </div>
      </div>

    </div>
    <!--container end-->

    <!--google map start-->
    <div class="contact-map">
      <div id="map-canvas" style="width: 100%; height: 400px">
      </div>
    </div>
    <!--google map end-->



{% endblock content %}

{% block postScripts %}
    <script>
      wow = new WOW(
        {
          boxClass:     'wow',      // default
          animateClass: 'animated', // default
          offset:       0          // default
        }
      )
        wow.init();
    </script>


    <script>
      $(document).ready(function() {
        //Set the carousel options
        $('#quote-carousel').carousel({
          pause: true,
          interval: 4000,
        }
                                     );
      }
                       );

      //google map
      function initialize() {
        var myLatlng = new google.maps.LatLng(41.388340, 2.113515); 
        var mapOptions = {
          zoom: 17,
          center: myLatlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
            var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
        var marker = new google.maps.Marker({
          position: myLatlng,
          map: map,
          title: 'Contact'
        }
                                           );
      }
      google.maps.event.addDomListener(window, 'load', initialize);



    </script>
{% endblock postScripts %}

web/templates/web/curso.html
{% extends 'web/base.html' %}

{% block title %}Curso | IEEE BCN SB{% endblock title %}


  {% block content %}

    <!--breadcrumbs start-->
    <div class="breadcrumbs">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-sm-4">
            <h1>
                {{ curso.title }}
            </h1>
          </div>
          <div class="col-lg-8 col-sm-8">
            <ol class="breadcrumb pull-right">
              <li>
                <a href="{% url 'web:index' %}">
                  Inicio
                </a>
              </li>
              <li>
                <a href="{% url 'web:cursos' %}">
                  Cursos
                </a>
              </li>
              <li class="active">
                Curso
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!--breadcrumbs end-->


    <!--container start-->
    <div class="container">
      <div class="row">
        <!--blog start-->
        <div class="col-lg-9 ">

        <div class="blog-item">
            <div class="row">
              <div class="col-lg-2 col-sm-2">
                <div class="date-wrap">
                  <span class="date">
                    {{ curso.date_start.day }}
                  </span>
                  <span class="month">
                    {{ curso.month }} {{ curso.date_start.year }}
                  </span>
                </div>

              </div>
              <div class="col-lg-10 col-sm-10">
                  {% if curso.img %}
                  <div class="blog-img">
                    <img src="{{ curso.img.url }}" alt="Imagen del tema del curso"/>
                  </div>
                  {% endif %}

              </div>
            </div>
            <div class="row">
              <div class="col-lg-2 col-sm-2 text-right">
                <div class="author">
                  Por
                  <a href="#">
                    {{ username }}
                  </a>
                </div>
              </div>
              <div class="col-lg-10 col-sm-10">
                <h1>
                    {{ curso.title }}
                </h1>
                <p>
                    {% autoescape off %}
                      {{ curso.description }}
                    {% endautoescape %}
                </p>
              </div>
            </div>
          </div>

        </div>

        <div class="col-lg-3">
          <div class="blog-side-item">
           <!-- Side content -->

          </div>
        </div>

        <!--blog end-->
      </div>

    </div>
    <!--container end-->

{% endblock content %}

{% block postScripts %}
  {{ block.super }}
      <script>
      wow = new WOW(
        {
          boxClass:     'wow',      // default
          animateClass: 'animated', // default
          offset:       0          // default
        }
      )
        wow.init();
    </script>
{% endblock postScripts %}

web/templates/web/index.html
{% extends 'web/base.html' %}
{% load staticfiles %}


{% block title %}IEEE BCN SB{% endblock title %}

{% block preScripts %}
  {{ block.super }}
{% endblock preScripts %}

  {% block content %}

    <!-- Sequence Modern Slider -->
    <div id="da-slider" class="da-slider">
    </div>


    <div class="container">
      <div class="row mar-b-50">
        <div class="col-md-12">
          <div class="text-center feature-head wow fadeInDown">
            <h1 class="">
              IEEE BCN SB
            </h1>

          </div>


          <div class="feature-box">
            <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
              <div class="feature-box-heading">
                <em>
                <img src="{% static "web/img/ieee.jpg" %}" alt="" width="80" height="90">

                </em>
                <h4>
                  <b>¿Que es el IEEE?</b>
                </h4>
              </div>
              <p class="text-center">
               IEEE es una asociación mundial de ingenieros con miles de miembros
                cuyo objetivo es hacer avanzar la ingeniería. <a href="{% url 'web:ieee' %}"> Mas infromación.</a>
              </p>
            </div>
            <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
              <div class="feature-box-heading">
                <em>
                  <img src="{% static "web/img/2.png" %}" alt="" width="100" height="100">
                </em>
                <h4>
                  <b>Proyectos</b>
                </h4>
              </div>
              <p class="text-center">
                Como actividad principal de la associación hacemos continuamente proyectos tecnológicos de todo tipo. <a href="{% url 'web:proyectos' %}">Averigua que se cuece!</a>
              </p>
            </div>
            <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
              <div class="feature-box-heading">
                <em>
                  <img src="{% static "web/img/3.png" %}" alt="" width="100" height="100">
                </em>
                <h4>
                  <b>Agenda</b>
                </h4>
              </div>
              <p class="text-center">
                Organizamos periódicamente actividades abiertas a todo el mundo como visitas organizadas a centros tecnológicos o cursos. <a href="{% url 'web:visitas' %}">No te pierdas nada.</a>
              </p>
            </div>
          </div>

          <!--feature end-->
        </div>
      </div>
    </div>


        <!--property start-->
      <div class="bg-lg">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-sm-6 text-center wow fadeInLeft">
            <img src="{% static "web/img/temp.jpg" %}" style="margin: 20px 10px 30px 10px" alt="En construcción">
          </div>
        </div>
      </div>
      </div>
    <!--property end-->



{% endblock content %}